export interface PriceItem {
  id: string;
  name: string;
  category: "bouquets" | "decor" | "jewellery" | "gifts";
  startingPrice: number | string;
  priceLabel: string;
  description: string;
  popularFor: string;
  badge?: string;
  href: string;
}

export const SNAPSHOT_PRICES: PriceItem[] = [
  // Bouquets
  {
    id: "simple-bouquets",
    name: "Fresh Flower Bouquets",
    category: "bouquets",
    startingPrice: 500,
    priceLabel: "From PKR 500",
    description: "Simple fresh flower bouquets with seasonal blooms and elegant paper wrap.",
    popularFor: "Everyday gifting, congratulations, birthdays",
    badge: "Budget Friendly",
    href: "/collections/bouquets",
  },
  {
    id: "single-rose",
    name: "Single Rose Bouquet",
    category: "bouquets",
    startingPrice: 1239,
    priceLabel: "From PKR 1,239",
    description: "Single long-stem rose beautifully wrapped — a minimal yet striking gesture.",
    popularFor: "Minimalist romance, subtle appreciation",
    badge: "Bestseller",
    href: "/collections/roses",
  },
  {
    id: "sunflower-bouquets",
    name: "Sunflower Bouquets",
    category: "bouquets",
    startingPrice: 1699,
    priceLabel: "From PKR 1,699",
    description: "Bright golden sunflowers paired with ruby spray roses and eucalyptus foliage.",
    popularFor: "Birthdays, get well soon, graduation",
    badge: "Trending",
    href: "/collections/sunflowers",
  },
  {
    id: "classic-rose-bouquets",
    name: "Classic Rose Bouquets (12–50 Stems)",
    category: "bouquets",
    startingPrice: 1499,
    priceLabel: "From PKR 1,499",
    description: "Imported Dutch velvet red roses with baby's breath and ribbon accents.",
    popularFor: "Anniversaries, proposals, Valentine's Day",
    badge: "Most Popular",
    href: "/collections/roses",
  },
  {
    id: "chocolate-bouquets",
    name: "Chocolate & Ferrero Bouquets",
    category: "bouquets",
    startingPrice: 2999,
    priceLabel: "From PKR 2,999",
    description: "Handcrafted Ferrero Rocher, Dairy Milk & KitKat bouquets nestled in florals.",
    popularFor: "Sweet celebrations, birthday surprises",
    badge: "Luxury Gifting",
    href: "/collections/gifts-cakes",
  },
  {
    id: "lily-bouquets",
    name: "Oriental Lily Bouquets",
    category: "bouquets",
    startingPrice: 3999,
    priceLabel: "From PKR 3,999",
    description: "Fragrant Casablanca lilies with luxury dual-tone wraps and satin ties.",
    popularFor: "High-end corporate gifting, VIP events",
    badge: "Grand Luxury",
    href: "/collections/bouquets",
  },
  {
    id: "crochet-bouquets",
    name: "Handmade Crochet Keepsake Bouquets",
    category: "bouquets",
    startingPrice: 999,
    priceLabel: "From PKR 999",
    description: "100% yarn-knitted floral blooms that never wilt or fade — an eternal memory.",
    popularFor: "Keepsake gifting, room decor",
    badge: "Everlasting",
    href: "/collections/bouquets",
  },
  {
    id: "artificial-bouquets",
    name: "Artificial Velvet Floral Bouquets",
    category: "bouquets",
    startingPrice: 800,
    priceLabel: "From PKR 800",
    description: "High-grade silk and velvet faux flowers for permanent display.",
    popularFor: "Office styling, long-term home aesthetics",
    href: "/collections/bouquets",
  },
  {
    id: "tulip-bouquets",
    name: "Imported Dutch Tulip Bouquets",
    category: "bouquets",
    startingPrice: 2999,
    priceLabel: "From PKR 2,999",
    description: "Direct-import Holland fresh tulips in crisp pastel tones.",
    popularFor: "Sophisticated luxury, Spring celebrations",
    badge: "Imported",
    href: "/collections/bouquets",
  },
  {
    id: "money-bouquets",
    name: "Custom Cash Money Bouquets",
    category: "bouquets",
    startingPrice: 2500,
    priceLabel: "Crafting from PKR 2,500",
    description: "Crisp PKR bank notes artistically folded into roses with fresh blooms.",
    popularFor: "Weddings, Eid salami, graduation gifts",
    badge: "Custom Made",
    href: "/collections/money-bouquets",
  },

  // Wedding & Event Décor
  {
    id: "wedding-car-decor",
    name: "Wedding Car Flower Decoration",
    category: "decor",
    startingPrice: 1500,
    priceLabel: "From PKR 1,500",
    description: "Simple satin ribbon styling up to full fresh Dutch rose bonnet cascades and handles.",
    popularFor: "Barat cars, bridal departure, groom cars",
    badge: "Express Setup",
    href: "/collections/wedding-decor",
  },
  {
    id: "wedding-room-decor",
    name: "Bridal Wedding Room Decoration",
    category: "decor",
    startingPrice: 6000,
    priceLabel: "From PKR 6,000",
    description: "Canopy bed styling, red rose petal carpets, fairy lights, and scented candles.",
    popularFor: "Suhag raat, newlywed bridal rooms",
    badge: "Signature",
    href: "/collections/wedding-decor",
  },
  {
    id: "mayon-decor",
    name: "Mayon Floral Décor & Backdrops",
    category: "decor",
    startingPrice: 10000,
    priceLabel: "From PKR 10,000",
    description: "Traditional golden-yellow marigold and sunflower backdrops with festive cushions.",
    popularFor: "Home mayon functions, intimate gatherings",
    href: "/collections/wedding-decor",
  },
  {
    id: "mehndi-decor",
    name: "Mehndi Stage & Seating Styling",
    category: "decor",
    startingPrice: 12000,
    priceLabel: "From PKR 12,000",
    description: "Vibrant festive stage setups, floral arches, hanging kaliras, and low dholki seating.",
    popularFor: "Mehndi nights, musical evenings",
    badge: "Custom Quote",
    href: "/collections/wedding-decor",
  },
  {
    id: "nikah-decor",
    name: "Nikah Ceremony Floral Styling",
    category: "decor",
    startingPrice: 15000,
    priceLabel: "From PKR 15,000",
    description: "Serene white and pastel floral backdrops, mirror tables, and signature floral curtains.",
    popularFor: "Formal nikah ceremonies, mosque setups",
    badge: "Premium",
    href: "/collections/wedding-decor",
  },
  {
    id: "wedding-lights",
    name: "House-Front Wedding Fairy Lights",
    category: "decor",
    startingPrice: 6000,
    priceLabel: "From PKR 6,000",
    description: "Warm-white exterior roofline and garden string illumination for shaadi homes.",
    popularFor: "Wedding week home ambiance",
    href: "/collections/wedding-decor",
  },
  {
    id: "birthday-room-decor",
    name: "Birthday Surprise Room Décor",
    category: "decor",
    startingPrice: 7000,
    priceLabel: "From PKR 7,000",
    description: "Helium balloon ceiling cascades, LED number lights, flower petals & backdrop rings.",
    popularFor: "Midnight birthday surprises, spouse celebrations",
    badge: "Surprise Ready",
    href: "/occasions/birthday",
  },
  {
    id: "walima-decor",
    name: "Walima Stage & Hall Décor",
    category: "decor",
    startingPrice: 25000,
    priceLabel: "Custom Quote",
    description: "Grand imported floral installations, crystal chandeliers, and catwalk styling.",
    popularFor: "Grand reception banquets",
    href: "/collections/wedding-decor",
  },

  // Floral Jewellery & Gajray
  {
    id: "gajray-pair",
    name: "Fresh Fragrant Gajray (Pair)",
    category: "jewellery",
    startingPrice: 370,
    priceLabel: "From PKR 370 / pair",
    description: "Fresh fragrant motia (jasmine) or red rose petal gajray tied with soft thread.",
    popularFor: "Mehndi, dholki, weddings, casual wear",
    badge: "Fresh Daily",
    href: "/collections/wedding-decor",
  },
  {
    id: "garlands-haar",
    name: "Floral Garlands / Mala / Haar",
    category: "jewellery",
    startingPrice: 300,
    priceLabel: "From PKR 300",
    description: "Traditional welcoming and wedding garlands in rose, motia, and marigold.",
    popularFor: "Groom haar, guest welcoming, VIP honors",
    href: "/collections/wedding-decor",
  },
  {
    id: "mehndi-jewellery-set",
    name: "Mehndi Floral Jewellery Accessories",
    category: "jewellery",
    startingPrice: 650,
    priceLabel: "From PKR 650",
    description: "Individual fresh flower earrings, matha patti, and wrist corsages for bridesmaids.",
    popularFor: "Dholki accessories, bridesmaid styling",
    href: "/collections/wedding-decor",
  },
  {
    id: "bridal-jewellery-set",
    name: "Complete Bridal Floral Jewellery Set",
    category: "jewellery",
    startingPrice: 1000,
    priceLabel: "From PKR 1,000",
    description: "Full coordinated bridal set including matha patti, earrings, necklace & double gajray.",
    popularFor: "Mehndi brides, mayon brides",
    badge: "Handcrafted",
    href: "/collections/wedding-decor",
  },

  // Gifts & Celebration Combos
  {
    id: "helium-balloons",
    name: "Helium Latex & Foil Balloons",
    category: "gifts",
    startingPrice: 200,
    priceLabel: "From PKR 200 / pc",
    description: "Floating metallic chrome balloons, heart foils, and personalized letter sets.",
    popularFor: "Surprise bouquet add-ons, room ceilings",
    href: "/collections/gifts-cakes",
  },
  {
    id: "teddy-bears",
    name: "Plush Soft Teddy Bears",
    category: "gifts",
    startingPrice: 1200,
    priceLabel: "From PKR 1,200",
    description: "Premium plush teddy bears from 1ft up to 4ft giant huggable sizes.",
    popularFor: "Romantic surprises, birthday gifts",
    href: "/collections/gifts-cakes",
  },
  {
    id: "gift-baskets",
    name: "Curated Celebration Gift Baskets",
    category: "gifts",
    startingPrice: 2500,
    priceLabel: "From PKR 2,500",
    description: "Wicker and cane baskets filled with chocolates, snacks, and fresh blooms.",
    popularFor: "Eid Mubarak, corporate gifts, family visits",
    badge: "Curated",
    href: "/collections/gifts-cakes",
  },
  {
    id: "cake-flowers-combo",
    name: "Fresh Cake & Flower Bouquet Combo",
    category: "gifts",
    startingPrice: 3999,
    priceLabel: "From PKR 3,999+",
    description: "Artisanal bakery chocolate fudge cake (2 lbs) paired with 12 fresh red roses.",
    popularFor: "Midnight birthdays, anniversaries",
    badge: "Top Rated",
    href: "/collections/gifts-cakes",
  },
];

export const FAQ_DATA = [
  {
    q: "What is the starting price of a flower bouquet in Lahore?",
    a: "Flower bouquet pricing in Lahore starts from PKR 500 for compact seasonal arrangements and PKR 1,239 for a single rose bouquet. Premium rose bouquets typically range between PKR 1,499 to PKR 5,500 depending on stem count (12 to 50 stems), flower origin (local vs imported Dutch velvet roses), and packaging details.",
  },
  {
    q: "What is the cheapest bouquet available at Lahore Bouquet?",
    a: "Our most budget-friendly bouquets start from PKR 500 for fresh local seasonal blooms or PKR 1,239 for a single rose. If you have a specific target budget (e.g. PKR 1,000 or PKR 1,500), message us on WhatsApp and our florists will craft the best-looking arrangement within your exact price range.",
  },
  {
    q: "How much does a sunflower bouquet cost in Lahore?",
    a: "Sunflower bouquet options start from PKR 1,699. Prices change depending on sunflower stem count, filler greens, and luxury parchment wrapping.",
  },
  {
    q: "What is the starting price of a chocolate bouquet in Lahore?",
    a: "Chocolate bouquets start from PKR 2,999 for fresh arrangements incorporating Ferrero Rocher, Cadbury Dairy Milk, or KitKat chocolates.",
  },
  {
    q: "How much does wedding car decoration cost in Lahore?",
    a: "Wedding car decoration starts from PKR 1,500 for elegant ribbon and floral bow styling. Comprehensive fresh flower bonnet cascades, door handle corsages, and rear window bouquets generally cost between PKR 3,500 and PKR 7,500 depending on car model and flower selection.",
  },
  {
    q: "What is the starting price for bridal room decoration in Lahore?",
    a: "Bridal wedding room decoration starts from PKR 6,000 for romantic bed styling with fresh rose petals, scented pillar candles, and soft fairy lighting. Grand canopy installations and full room transformations range from PKR 12,000 to PKR 25,000.",
  },
  {
    q: "What is the starting price of mehndi floral jewellery?",
    a: "Individual mehndi floral accessories (such as gajray, earrings, or rings) start from PKR 650. Complete coordinated bridal floral jewellery sets — including matha patti, jhumkas, choker necklace, and matching gajray — start from PKR 1,000 to PKR 2,500.",
  },
  {
    q: "What are fresh gajray prices in Lahore?",
    a: "Fresh jasmine (motia) and red rose petal gajray start from PKR 370 per pair. Custom double-layered thick gajray with tuberose strings or gold tinsel accents cost between PKR 700 to PKR 1,200 per pair.",
  },
  {
    q: "What is the starting price of flower garlands / mala / haar?",
    a: "Traditional flower garlands start from PKR 300 for lighter rose petal or marigold styles. Thick, royal groom haar featuring imported Dutch red roses with gold borders range from PKR 1,500 to PKR 4,000.",
  },
  {
    q: "Do you offer same-day express delivery in Lahore, and what are delivery charges?",
    a: "Yes! We provide 2–5 hours same-day express delivery across DHA, Gulberg, Bahria Town, Model Town, Johar Town, Cantt, and all Lahore sectors. Standard delivery is free on qualifying orders, with nominal express slots (PKR 250–350) for midnight and guaranteed 2-hour rush slots.",
  },
];
